version: 4.0.0

environment:
  nuget_token:
      secure: ymSZUTB0duopLgboXD+JEuGFV12mdf+uCamXwPCSZplxSWG3iwznFSfU+AlPFrYy

branches:
  only:
  - master

skip_branch_with_pr: true
skip_tags: true

max_jobs: 1
image: Visual Studio 2017
configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

matrix:
  fast_finish: true

build_script:
  - cmd: dotnet restore
  - cmd: dotnet build NooBIT.Model.sln -c Release /p:DebugType=Full
  - cmd: dotnet pack -c Release --no-build --include-symbols -o ..\..\artifacts /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
  - cmd: dotnet nuget push artifacts\NooBIT.Model.%APPVEYOR_BUILD_VERSION%.nupkg -k %nuget_token% -s https://www.nuget.org/api/v2/package
  - cmd: dotnet nuget push artifacts\NooBIT.Model.MediatR.%APPVEYOR_BUILD_VERSION%.nupkg -k %nuget_token% -s https://www.nuget.org/api/v2/package
  - cmd: dotnet nuget push artifacts\NooBIT.Model.EntityFrameworkCore.%APPVEYOR_BUILD_VERSION%.nupkg -k %nuget_token% -s https://www.nuget.org/api/v2/package

test: off
